[project]
name = "postcond-bench"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.11,<3.15"
dependencies = [
    "tqdm (>=4.67.1,<5.0.0)",
    "tree-sitter (>=0.25.1,<0.26.0)",
    "tree-sitter-python (>=0.23.6,<0.24.0)",
    "fuzzywuzzy (>=0.18.0,<0.19.0)",
    "tiktoken (>=0.11.0,<0.12.0)",
    "openai (==2.6.1)",
    "langdetect (>=1.0.9,<2.0.0)",
    "toml (>=0.10.2,<0.11.0)",
    "pygit2 (>=1.18.2,<2.0.0)",
    "python-levenshtein (>=0.27.1,<0.28.0)",
    "debugpy (>=1.8.16,<2.0.0)",
    "tree-sitter-java (>=0.23.5,<0.24.0)",
    "transformers (>=4.56.0,<5.0.0)",
    "anthropic (>=0.65.0,<0.66.0)",
    "flask (>=3.1.2,<4.0.0)",
    "uuid6 (>=2025.0.1,<2026.0.0)",
    "cffi (>=2.0.0,<3.0.0)",
    "libcst (>=1.8.5,<2.0.0)",
    "numpy (>=2.3.4,<3.0.0)",
    "boto3 (>=1.40.68,<2.0.0)",
    "matplotlib (>=3.10.7,<4.0.0)",
    "z3-solver (>=4.15.4.0,<5.0.0.0)",
    "reportlab (>=4.4.9,<5.0.0)",
    "autogen-agentchat (>=0.7.5,<0.8.0)",
    "autogen-ext[openai] (>=0.7.5,<0.8.0)",
    "openpyxl (>=3.1.5,<4.0.0)",
    "crosshair-tool (>=0.0.102,<0.0.103)",
    "icontract (>=2.7.3,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "postcond-bench"
version = "0.1.0"
package-mode = false