import os, json, math, random
import numpy as np
from typing import List, Dict, Tuple, Optional, Set
from itertools import combinations
from multiprocessing import Pool

from src.mutation.mutmut import generate_mutants_for_method as python_mut
from src.mutation.pit import generate_mutants_for_method as java_mut
from src.ds import Method

KFS = ["jml_fail", "icontract_fail"]
LANGUAGES = ["python", "java"]


# ===================== IO =====================
def read_benchmark_dir(p: str, save_mem: bool = True) -> List[Method]:
    methods: List[Method] = []
    for fn in os.listdir(p):
        fp = os.path.join(p, fn)
        if not os.path.isfile(fp):
            continue
        with open(fp, "r", encoding="utf-8") as f:
            m = Method.from_dict(json.load(f))
            if save_mem:
                m.repo.env_config = None
                m.repo.failed_tests = None
                # keep mutants + mutant_tags
                m.cover_tests = None
                m.postconds = None
                m.responses = None
            methods.append(m)
    return methods


def load_all_methods_for_model(step_dir: str, models: List[str]) -> List[Method]:
    all_methods: List[Method] = []
    for model_name in models:
        for folder_name in os.listdir(step_dir):
            if not folder_name.startswith("9."):
                continue
            if folder_name.startswith(f"9.{model_name}--"):
                all_methods.extend(
                    read_benchmark_dir(os.path.join(step_dir, folder_name), save_mem=True)
                )
    return all_methods


# ===================== core metrics =====================
def calculate_pass_1(n: int, c: int) -> float:
    return 0.0 if n <= 0 else c / n


def _is_complete_under_subset(
    corr_res: str,
    comp_res: List[str],
    ref_mutant_kill: List[str],
    selected_mutant_indices: List[int],
) -> bool:
    """
    IMPORTANT: empty selected set is vacuously complete (if corr passed).
    This restores monotonicity: removing mutants cannot decrease completeness.
    """
    if corr_res != "passed":
        return False
    if len(selected_mutant_indices) == 0:
        return True
    if len(comp_res) == 0:
        return False
    assert len(comp_res) == len(ref_mutant_kill), (len(comp_res), len(ref_mutant_kill))

    for i in selected_mutant_indices:
        r_f = ref_mutant_kill[i]
        f = comp_res[i]
        if r_f in KFS and f not in KFS:
            return False
    return True


# ===================== mutant helpers =====================
def norm_code(s: str) -> str:
    return "\n".join(line.rstrip() for line in s.strip().splitlines())


def tags_set(tags: List[str]) -> Set[str]:
    return set(tags)


def has_rule(tags: List[str]) -> bool:
    return "rule" in tags_set(tags)


def has_llm(tags: List[str]) -> bool:
    return "llm" in tags_set(tags)


def is_rule_only(tags: List[str]) -> bool:
    s = tags_set(tags)
    return ("rule" in s) and ("llm" not in s)


def is_llm_only(tags: List[str]) -> bool:
    s = tags_set(tags)
    return ("llm" in s) and ("rule" not in s)


def get_eval_mutants_and_tags(m: Method) -> Optional[Tuple[List[str], List[List[str]]]]:
    if not hasattr(m, "mutants") or not hasattr(m, "mutant_tags"):
        return None
    muts = getattr(m, "mutants")
    tags = getattr(m, "mutant_tags")
    if not isinstance(muts, list) or not (len(muts) == 0 or isinstance(muts[0], str)):
        return None
    if not isinstance(tags, list) or not (len(tags) == 0 or isinstance(tags[0], list)):
        return None
    if len(muts) != len(tags):
        return None
    return muts, tags


def method_key(m: Method) -> str:
    return getattr(m, "id", None) or f"{m.repo.github_path}::{m.file}::{m.start_line}-{m.end_line}"


# ===================== rule mutator name inference (string match) =====================
def gen_rule_mutator_map_for_method(m: Method) -> Dict[str, str]:
    """
    mapping: norm(mutant_code) -> mutator_name
    generated by rule-based generator for this method.
    """
    src = m.content
    if m.repo.language == "python":
        muts, names = python_mut(src, w_mut_name=True)
    elif m.repo.language == "java":
        muts, names = java_mut(src, w_mut_name=True)
    else:
        return {}

    mp: Dict[str, str] = {}
    for s, nm in zip(muts, names):
        k = norm_code(s)
        if k not in mp:
            mp[k] = nm
    return mp


def infer_rule_mutator_types_for_eval(
    m: Method,
    eval_mutants: List[str],
    eval_tags: List[List[str]],
    rule_map: Dict[str, str],
) -> List[Optional[str]]:
    """
    Only define a rule-operator type for RULE-ONLY mutants:
      tags contains "rule" and does NOT contain "llm".
    If rule-only but cannot match: "other_rule".
    Otherwise: None (never removed by rule-operator ablations).
    """
    out: List[Optional[str]] = []
    for s, tags in zip(eval_mutants, eval_tags):
        if is_rule_only(tags):
            nm = rule_map.get(norm_code(s))
            out.append(nm if nm is not None else "other_rule")
        else:
            out.append(None)
    return out


# ===================== selection policies =====================
def selected_indices_baseline(total_muts: int) -> List[int]:
    return list(range(total_muts))


def selected_indices_exclude_one_rule_operator(
    rule_types: List[Optional[str]],
    excluded_op: str,
) -> Tuple[List[int], int]:
    excluded_idx = [i for i, t in enumerate(rule_types) if t == excluded_op]
    excluded_set = set(excluded_idx)
    selected = [i for i in range(len(rule_types)) if i not in excluded_set]
    return selected, len(excluded_idx)


def selected_indices_exclude_rule_operator_set(
    rule_types: List[Optional[str]],
    excluded_ops: Set[str],
) -> Tuple[List[int], int]:
    excluded_idx = [i for i, t in enumerate(rule_types) if (t is not None and t in excluded_ops)]
    excluded_set = set(excluded_idx)
    selected = [i for i in range(len(rule_types)) if i not in excluded_set]
    return selected, len(excluded_idx)


def selected_indices_exclude_half_llm_keep_rule(
    eval_tags: List[List[str]],
    rng: random.Random,
) -> Tuple[List[int], int, int]:
    """
    Randomly exclude half of LLM-ONLY mutants (tags has llm but not rule).
    Mutants that also have rule are protected (never removed).
    Returns:
      selected_indices, removed_count, candidate_llm_only_count
    """
    llm_only_candidates = [i for i, tags in enumerate(eval_tags) if is_llm_only(tags)]
    candidate_count = len(llm_only_candidates)
    if candidate_count == 0:
        return list(range(len(eval_tags))), 0, 0

    k = candidate_count // 2
    remove_idx = set(rng.sample(llm_only_candidates, k=k))
    selected = [i for i in range(len(eval_tags)) if i not in remove_idx]
    return selected, len(remove_idx), candidate_count


def selected_indices_exclude_all_rule_only(
    eval_tags: List[List[str]],
) -> Tuple[List[int], int]:
    remove_idx = {i for i, tags in enumerate(eval_tags) if is_rule_only(tags)}
    selected = [i for i in range(len(eval_tags)) if i not in remove_idx]
    return selected, len(remove_idx)


def selected_indices_exclude_all_llm_only(
    eval_tags: List[List[str]],
) -> Tuple[List[int], int]:
    remove_idx = {i for i, tags in enumerate(eval_tags) if is_llm_only(tags)}
    selected = [i for i in range(len(eval_tags)) if i not in remove_idx]
    return selected, len(remove_idx)


# ===================== compute Comp@1 under a selection rule =====================
def comp_at_1_with_selector(
    methods: List[Method],
    selector_fn,
) -> Dict[str, float]:
    """
    selector_fn signature:
      selector_fn(m: Method, total_muts: int) -> (selected_indices: List[int], removed_count: int, meta: dict)
    """
    assert methods
    generate_num = methods[0].generate_num
    assert all(m.generate_num == generate_num for m in methods)
    assert generate_num in (1, 5)

    pass1_list = []
    total_muts_list = []
    removed_list = []

    for m in methods:
        total_muts = len(m.ref_mutant_kill) if m.ref_mutant_kill is not None else 0
        total_muts_list.append(total_muts)

        if total_muts <= 0:
            pass1_list.append(0.0)
            removed_list.append(0)
            continue

        selected, removed, _meta = selector_fn(m, total_muts)

        comp_count = 0
        for corr_res, comp_res in zip(m.postcond_corr, m.mutant_kill):
            if _is_complete_under_subset(corr_res, comp_res, m.ref_mutant_kill, selected):
                comp_count += 1

        pass1_list.append(calculate_pass_1(generate_num, comp_count))
        removed_list.append(removed)

    return {
        "method_count": float(len(methods)),
        "avg_total_mutants": float(np.mean(total_muts_list)) if total_muts_list else 0.0,
        "avg_removed_mutants": float(np.mean(removed_list)) if removed_list else 0.0,
        "comp_1": float(np.mean(pass1_list)) if pass1_list else 0.0,
    }


# ===================== per-language experiment =====================
def filter_methods(methods: List[Method], lang: str) -> List[Method]:
    return [m for m in methods if m.repo.language == lang]


def run_language_ops_experiments(all_methods: List[Method], lang: str) -> Dict:
    ms = filter_methods(all_methods, lang)
    if not ms:
        return {"language": lang, "baseline": None}

    # Cache per method: rule_map and rule_types
    rule_map_cache: Dict[str, Dict[str, str]] = {}
    rule_types_cache: Dict[str, Optional[List[Optional[str]]]] = {}

    def get_rule_types(m: Method, total_muts: int) -> Optional[List[Optional[str]]]:
        key = method_key(m)
        cached = rule_types_cache.get(key)
        if cached is not None or key in rule_types_cache:
            return cached

        mt = get_eval_mutants_and_tags(m)
        if mt is None:
            rule_types_cache[key] = None
            return None
        eval_muts, eval_tags = mt
        if len(eval_muts) != total_muts:
            rule_types_cache[key] = None
            return None

        rmap = rule_map_cache.get(key)
        if rmap is None:
            rmap = gen_rule_mutator_map_for_method(m)
            rule_map_cache[key] = rmap

        rule_types = infer_rule_mutator_types_for_eval(m, eval_muts, eval_tags, rmap)
        if len(rule_types) != total_muts:
            rule_types_cache[key] = None
            return None

        rule_types_cache[key] = rule_types
        return rule_types

    # -------- (1) baseline --------
    def baseline_selector(m: Method, total_muts: int):
        return selected_indices_baseline(total_muts), 0, {}

    baseline = comp_at_1_with_selector(ms, baseline_selector)
    baseline_comp = baseline["comp_1"]

    # -------- rule-operator universe (rule-only mutants only) --------
    op_set = set()
    for m in ms:
        total_muts = len(m.ref_mutant_kill) if m.ref_mutant_kill is not None else 0
        if total_muts <= 0:
            continue
        rule_types = get_rule_types(m, total_muts)
        if rule_types is None:
            continue
        for t in rule_types:
            if t is None:
                continue
            op_set.add(t)

    ops_sorted = sorted(op_set)

    # -------- (2) exclude ONE operator --------
    one_op_results: Dict[str, Dict[str, float]] = {}
    for op in ops_sorted:
        def make_selector(excluded_op: str):
            def _sel(m: Method, total_muts: int):
                rule_types = get_rule_types(m, total_muts)
                if rule_types is None:
                    return selected_indices_baseline(total_muts), 0, {"note": "no_rule_types"}
                selected, removed = selected_indices_exclude_one_rule_operator(rule_types, excluded_op)
                return selected, removed, {}
            return _sel

        r = comp_at_1_with_selector(ms, make_selector(op))
        one_op_results[op] = {
            **r,
            "diff_from_baseline": float(r["comp_1"] - baseline_comp),
        }

    # -------- (3) exclude FIVE operators: all combinations --------
    five_op_stats = None
    if len(ops_sorted) >= 5:
        comp_vals = []
        removed_vals = []
        for comb in combinations(ops_sorted, 5):
            excluded_ops = set(comb)

            def make_selector_set(ex_ops: Set[str]):
                def _sel(m: Method, total_muts: int):
                    rule_types = get_rule_types(m, total_muts)
                    if rule_types is None:
                        return selected_indices_baseline(total_muts), 0, {"note": "no_rule_types"}
                    selected, removed = selected_indices_exclude_rule_operator_set(rule_types, ex_ops)
                    return selected, removed, {}
                return _sel

            rr = comp_at_1_with_selector(ms, make_selector_set(excluded_ops))
            comp_vals.append(rr["comp_1"])
            removed_vals.append(rr["avg_removed_mutants"])

        five_op_stats = {
            "num_ops_total": int(len(ops_sorted)),
            "num_combinations": int(math.comb(len(ops_sorted), 5)),
            "comp_1_mean": float(np.mean(comp_vals)) if comp_vals else 0.0,
            "comp_1_std": float(np.std(comp_vals, ddof=0)) if comp_vals else 0.0,
            "avg_removed_mutants_mean": float(np.mean(removed_vals)) if removed_vals else 0.0,
            "avg_removed_mutants_std": float(np.std(removed_vals, ddof=0)) if removed_vals else 0.0,
            "diff_mean_from_baseline": float((float(np.mean(comp_vals)) if comp_vals else 0.0) - baseline_comp),
        }
    else:
        five_op_stats = {
            "num_ops_total": int(len(ops_sorted)),
            "num_combinations": 0,
            "comp_1_mean": None,
            "comp_1_std": None,
            "avg_removed_mutants_mean": None,
            "avg_removed_mutants_std": None,
            "diff_mean_from_baseline": None,
        }

    # -------- (4) exclude HALF LLM-only mutants (50 runs), keep rule-tag mutants --------
    REPEATS = 50
    BASE_SEED = 20260217 + (0 if lang == "python" else 9999)

    comp_vals = []
    removed_vals = []
    for r in range(REPEATS):
        rng = random.Random(BASE_SEED + r)

        def make_llm_half_selector(rng_local: random.Random):
            def _sel(m: Method, total_muts: int):
                mt = get_eval_mutants_and_tags(m)
                if mt is None:
                    return selected_indices_baseline(total_muts), 0, {"note": "no_tags"}
                _muts, tags = mt
                if len(tags) != total_muts:
                    return selected_indices_baseline(total_muts), 0, {"note": "len_mismatch"}
                selected, removed, _cand = selected_indices_exclude_half_llm_keep_rule(tags, rng_local)
                return selected, removed, {}
            return _sel

        rr = comp_at_1_with_selector(ms, make_llm_half_selector(rng))
        comp_vals.append(rr["comp_1"])
        removed_vals.append(rr["avg_removed_mutants"])

    llm_half_stats = {
        "repeats": REPEATS,
        "comp_1_mean": float(np.mean(comp_vals)) if comp_vals else 0.0,
        "comp_1_std": float(np.std(comp_vals, ddof=0)) if comp_vals else 0.0,
        "avg_removed_mutants_mean": float(np.mean(removed_vals)) if removed_vals else 0.0,
        "avg_removed_mutants_std": float(np.std(removed_vals, ddof=0)) if removed_vals else 0.0,
        "diff_mean_from_baseline": float((float(np.mean(comp_vals)) if comp_vals else 0.0) - baseline_comp),
    }

    # -------- (5) exclude ALL rule-only OR exclude ALL llm-only (both always kept) --------
    def exclude_all_rule_only_selector(m: Method, total_muts: int):
        mt = get_eval_mutants_and_tags(m)
        if mt is None:
            return selected_indices_baseline(total_muts), 0, {"note": "no_tags"}
        _muts, tags = mt
        if len(tags) != total_muts:
            return selected_indices_baseline(total_muts), 0, {"note": "len_mismatch"}
        selected, removed = selected_indices_exclude_all_rule_only(tags)
        return selected, removed, {}

    def exclude_all_llm_only_selector(m: Method, total_muts: int):
        mt = get_eval_mutants_and_tags(m)
        if mt is None:
            return selected_indices_baseline(total_muts), 0, {"note": "no_tags"}
        _muts, tags = mt
        if len(tags) != total_muts:
            return selected_indices_baseline(total_muts), 0, {"note": "len_mismatch"}
        selected, removed = selected_indices_exclude_all_llm_only(tags)
        return selected, removed, {}

    excl_all_rule_only = comp_at_1_with_selector(ms, exclude_all_rule_only_selector)
    excl_all_llm_only = comp_at_1_with_selector(ms, exclude_all_llm_only_selector)

    excl_all_stats = {
        "exclude_all_rule_only": {
            **excl_all_rule_only,
            "diff_from_baseline": float(excl_all_rule_only["comp_1"] - baseline_comp),
        },
        "exclude_all_llm_only": {
            **excl_all_llm_only,
            "diff_from_baseline": float(excl_all_llm_only["comp_1"] - baseline_comp),
        },
    }

    return {
        "language": lang,
        "baseline": baseline,                           # (1)
        "rule_ops": ops_sorted,
        "exclude_one_op": one_op_results,               # (2)
        "exclude_five_ops": five_op_stats,              # (3)
        "exclude_half_llm_keep_rule": llm_half_stats,   # (4)
        "exclude_all_rule_or_llm_only": excl_all_stats, # (5)
    }


# ===================== main =====================
def main():
    STEP_DIR = "data/step"
    MODELS = ["gpt-5", "claude-sonnet-4-5", "llama-4-maverick", "Qwen3-32B", "gemma-3-27b"]
    out_path = "data/ablation_ops_and_llm_half_plus_exclude_all.json"

    all_methods = load_all_methods_for_model(STEP_DIR, MODELS)
    print(f"[load] methods={len(all_methods)}")

    args = [(all_methods, lang) for lang in LANGUAGES]
    with Pool(processes=min(len(args), 2)) as pool:
        results = pool.starmap(run_language_ops_experiments, args)

    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(results, f, ensure_ascii=False, indent=2)

    for r in results:
        print(f"\n=== {r['language'].upper()} ===")
        b = r["baseline"]
        if b is None:
            print("no methods")
            continue
        print(f"(1) baseline Comp@1 = {b['comp_1']:.4f}  (avg_total_mutants={b['avg_total_mutants']:.2f})")

        one = r["exclude_one_op"]
        items = [(op, d["comp_1"], d["diff_from_baseline"], d["avg_removed_mutants"]) for op, d in one.items()]
        items.sort(key=lambda x: x[2])  # diff asc
        print("\n(2) exclude ONE rule-operator:")
        for op, comp1, diff, rm in items:
            print(f"| {op} | {comp1:.4f} (+{(comp1/b['comp_1']-1) * 100:.1f}%) | {rm:.2f} |")

        five = r["exclude_five_ops"]
        print("\n(3) exclude FIVE rule-operators (all combinations):")
        if five["num_combinations"] == 0:
            print("  not enough operators to form C(n,5)")
        else:
            print(
                f"  ops_total={five['num_ops_total']}  combos={five['num_combinations']}\n"
                f"  Comp@1 mean={five['comp_1_mean']:.4f}  std={five['comp_1_std']:.4f}  "
                f"Δ_mean={five['diff_mean_from_baseline']:+.4f}\n"
                f"  removed(avg) mean={five['avg_removed_mutants_mean']:.2f}  std={five['avg_removed_mutants_std']:.2f}"
            )

        llm = r["exclude_half_llm_keep_rule"]
        print("\n(4) exclude HALF LLM-only mutants (50 runs, rule-tag protected):")
        print(
            f"  Comp@1 mean={llm['comp_1_mean']:.4f}  std={llm['comp_1_std']:.4f}  "
            f"Δ_mean={llm['diff_mean_from_baseline']:+.4f}\n"
            f"  removed(avg) mean={llm['avg_removed_mutants_mean']:.2f}  std={llm['avg_removed_mutants_std']:.2f}"
        )

        ex = r["exclude_all_rule_or_llm_only"]
        r_only = ex["exclude_all_rule_only"]
        l_only = ex["exclude_all_llm_only"]
        print("\n(5) exclude ALL rule-only vs ALL llm-only (both-tag never removed):")
        print(
            f"  -all rule-only: Comp@1={r_only['comp_1']:.4f}  Δ={r_only['diff_from_baseline']:+.4f}  "
            f"removed(avg)={r_only['avg_removed_mutants']:.2f}"
        )
        print(
            f"  -all llm-only : Comp@1={l_only['comp_1']:.4f}  Δ={l_only['diff_from_baseline']:+.4f}  "
            f"removed(avg)={l_only['avg_removed_mutants']:.2f}"
        )

    print(f"\n[done] wrote {out_path}")


if __name__ == "__main__":
    main()
